---
title: "Manipulate"
author: "Sarah Friesen"
date: "6/21/2021"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: "show"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Read online table

### Download table (*.csv)

```{r}
# set variables
csv_url  <- "https://oceanview.pfeg.noaa.gov/erddap/tabledap/cciea_AC.csv"
dir_data <- "data"

# derived variables
csv <- file.path(dir_data, basename(csv_url))

# create directory
dir.create(dir_data)

# download file
download.file(csv_url, csv)

```

### Read table `read_csv()`

```{r}
# attempt to read csv
d <- read.csv(csv)

# show the data frame
#d

# read csv by skipping first two lines, so no header
d <- read.csv(csv, skip = 2, header = FALSE)
#d

# update data frame to original column names
names(d) <- names(read.csv(csv))
#d
```
### Show table `DT::datatable()`
```{r}
# show table
DT::datatable(d)
```


## Wrangle data

### Manipulate with `dplyr`
```{r}
library(DT)
library(dplyr)

d <- d %>% 
  # tibble
  tibble() %>% 
  # mutate time
  mutate(
    time = as.Date(substr(time, 1, 10))) %>% 
  # select columns
  select(
    time, 
    starts_with("total_fisheries_revenue")) %>% 
  # filter rows
  filter(
    time >= as.Date("1981-01-01"))

datatable(d)
```

### Tidy with `tidyr`
```{r}
library(tidyr)

# convert from wide to long table
d <- d %>% 
  pivot_longer(-time)

datatable(d)
```

### Summarize with `dplyr` - what is the average fishing revenue per region?
```{r}
library(stringr)

d <- d %>% 
  mutate(
    region = str_replace(name, "total_fisheries_revenue_", "")) %>% 
  select(time, region, value)
datatable(d)

d_sum <- d %>% 
  group_by(region) %>% 
  summarize(
    avg_revenue = mean(value))
datatable(d_sum) %>% 
  formatCurrency("avg_revenue")
```

### Apply functions with `purrr` on a `nest`'ed `tibble` - what is the trend over time for fishing revenue by region?
```{r}
library(purrr)

n <- d %>% 
  group_by(region) %>% 
  nest(
    data = c(time, value))
n

n <- n %>% 
  mutate(
    # create linear model within each nested tibble
    lm    = map(data, function(d){
      lm(value ~ time, d) } ),
    # extract coefficient from each linear model to show trend
    trend = map_dbl(lm, function(m){
      coef(summary(m))["time","Estimate"] }))
n
# cut out all columns but region and trend coefficient
n %>% 
  select(region, trend) %>% 
  datatable()
```